logging.config=classpath:logback-base.xml
pn.env.runtime=PROD
spring.application.name=PN-SafeStorage
#Setting CloudWatch logging level to info, to make CloudWatchMetricPublisher logs visible.
logging.level.software.amazon.awssdk.metrics.publishers.cloudwatch=info

# Parametri di configurazione del TaskExecutor di Spring Boot
pn.ss.task.execution.pool.max-size=${PnSsTaskExecutionPoolMaxSize}
pn.ss.task.execution.pool.core-size=${PnSsTaskExecutionPoolCoreSize}
pn.ss.task.execution.pool.queue-capacity=${PnSsTaskExecutionPoolQueueCapacity}

spring.codec.max-in-memory-size=${SpringCodecMaxInMemorySize:10000000}

logging.level.it.pagopa.pnss=${PnSsLoggingLevelRoot:debug}
#logging.level.org.springframework.web = DEBUG

# Several ResponseStatusException found. If this prop is not set the reason of the exception is not shown in the api response body
server.error.include-message=always

spring.task.scheduling.pool.size=3
management.endpoints.web.exposure.include=health,metrics,loggers

#Sqs timeout delta
pn.ss.sqs.timeout.percent=${PnSsSqsTimeoutPercent}
pn.ss.sqs.timeout.managedQueues=${PnSsSqsTimeoutManagedQueues}
pn.ss.sqs.timeout.default-seconds=${PnSsSqsTimeoutDefaultSeconds}

#Sqs
pn.ss.sqs.retry.strategy.max-attempts=${PnSsSqsRetryStrategyMaxAttempts:3}
pn.ss.sqs.retry.strategy.min-backoff=${PnSsSqsRetryStrategyMinBackoff:3}

#Sqs EventHandler
pn.ss.sqs.event-handler.retry.strategy.max-attempts=${PnSsSqsEventHandlerRetryStrategyMaxAttempts:3}
pn.ss.sqs.event-handler.retry.strategy.min-backoff=${PnSsSqsEventHandlerRetryStrategyMinBackoff:3}

pn.ss.statemachine.retry.strategy.max-attempts=${PnSsStateMachineRetryStrategyMaxAttempts:3}
pn.ss.statemachine.retry.strategy.min-backoff=${PnSsStateMachineRetryStrategyMinBackoff:3}

##########################
###   PnSsConfig       ###
##########################

# Bucket
pn.ss.bucket.hot-name=${PnSsBucketName:PnSsBucketName}
pn.ss.bucket.stage-name=${PnSsStagingBucketName:PnSsStagingBucketName}

# Dynamo - Repository manager tables
pn.ss.dynamo.repository-manager.anagrafica-client-name=${PnSsTableNameAnagraficaClient:pn-SsAnagraficaClient}
pn.ss.dynamo.repository-manager.tipologie-documenti-name=${PnSsTableNameTipologieDocumenti:pn-SsTipologieDocumenti}
pn.ss.dynamo.repository-manager.documenti-name=${PnSsTableNameDocumenti:pn-SsDocumenti}
pn.ss.dynamo.repository-manager.scadenza-documenti-name=${PnSsTableNameScadenzaDocumenti:pn-SsScadenzaDocumenti}
pn.ss.dynamo.repository-manager.tags-name=${PnSsTableNameTags:pn-SsTags}

# Dynamo - Event stream
pn.ss.dynamo.event-stream.document-name=${PnSsTableDocumentiStreamArn:PnSsTableDocumentiStreamArn}
pn.ss.dynamo.event-stream.table-metadata=${PnSsTableDocumentiStreamMetadatiTable:TableDocumentiStreamMetadatiTable}

# Dynamo - Retry strategy
pn.ss.dynamo.retry-strategy.max-attempts=${PnSsDynamoRetryStrategyMaxAttempts:3}
pn.ss.dynamo.retry-strategy.min-backoff=${PnSsDynamoRetryStrategyMinBackoff:3}

# Sqs - Availability
pn.ss.sqs.availability.sqs-name=${PnSsQueueNameAvailability:pn-ss-availability-events-queue}

# Event bridge
pn.ss.event-bridge.disponibilita-documenti-name=${PnSsEventBusNameExternalNotification:Pn-Ss-Notifications-Bus}

# Endpoint - State machine
pn.ss.endpoint.state-machine.base-path=/statemachinemanager
pn.ss.endpoint.state-machine.container-base-url=${StateMachineBaseUrl:http://localhost:8082}
pn.ss.endpoint.state-machine.validate=${pn.ss.endpoint.state-machine.base-path}/validate/{processId}/{currStatus}

# Gestore repository - Retry strategy
pn.ss.gestore-repository.retry-strategy.max-attempts=${PnSsGestoreRepositoryRetryStrategyMaxAttempts:3}
pn.ss.gestore-repository.retry-strategy.min-backoff=${PnSsGestoreRepositoryRetryStrategyMinBackoff:3}

# S3 - Retry strategy
pn.ss.s3.retry-strategy.max-attempts=${PnSsS3RetryStrategyMaxAttempts:3}
pn.ss.s3.retry-strategy.min-backoff=${PnSsS3RetryStrategyMinBackoff:3}

# Client interni - Endpoint
pn.ss.client-interni.endpoint.doc-client=/safestorage/internal/v1/documents/%s
pn.ss.client-interni.endpoint.doc-client-post=/safestorage/internal/v1/documents
pn.ss.client-interni.endpoint.user-configuration=/safestorage/internal/v1/userConfigurations/%s
pn.ss.client-interni.endpoint.scadenza-documenti-post=/safestorage/internal/v1/scadenza-documenti
pn.ss.client-interni.endpoint.configuration-api-documents-config=/safe-storage/v1/configurations/documents-types
pn.ss.client-interni.endpoint.doc-types=/safestorage/internal/v1/doctypes/%s
pn.ss.client-interni.endpoint.tags-get=/safestorage/internal/v1/tags/%s
pn.ss.client-interni.endpoint.tags-put=/safestorage/internal/v1/documents/%s/tags

# Client interni - Header, query param, base url, jetty
pn.ss.client-interni.header.api-key=x-api-key
pn.ss.client-interni.header.pagopa-safestorage-cx-id=x-pagopa-safestorage-cx-id
#Header related to the correlationID in microservices calls
pn.ss.client-interni.header.correlation-id=x-pagopa-pn-cx-id
pn.ss.client-interni.query-param.presigned-url-trace-id=x-amzn-trace-id
pn.ss.client-interni.base-url=${InternalBaseUrl:http://localhost:8080}
pn.ss.client-interni.jetty.max-connections-per-destination=${maxConnectionsPerDestination:200}

# Retention
#ATTENZIONE: autorizzazione interna (vedi trasformazione file)
pn.ss.retention.default-internal-api-key-value=internal-api.key
#ATTENZIONE: autorizzazione interna (vedi trasformazione file)
pn.ss.retention.default-internal-client-id-value=internal
pn.ss.retention.object-lock-retention-mode=${PnSsBucketLockRetentionMode:GOVERNANCE}
pn.ss.retention.days-to-ignore=${PnSsPreloadedDocsRetentionDays:7}

# Uri builder
pn.ss.uri-builder.presigned-url.duration-minutes-upload=${DurationMinutesUpload:60}
pn.ss.uri-builder.presigned-url.duration-minutes-download=${DurationMinutesDownload:60}
pn.ss.uri-builder.presigned-url.checksum-sha256-header=checksum-sha256
pn.ss.uri-builder.stay-hot-bucket-time-days=${stayHotTime:2}
pn.ss.uri-builder.get-file-with-patch-configuration=${PnSsUriBuilderGetFileWithPatchConfiguration:NONE}
#Http header related to the S3 headObjectResponse
pn.ss.uri-builder.restore-request-date-header-name=x-amz-restore-request-date
pn.ss.uri-builder.max-restore-time-cold=${PnSsGlacierMaxRestoreTime:18000}
pn.ss.uri-builder.initial-new-document-state=BOOKED

##########################
###   CloudWatch       ###
##########################

pn.ss.sign.cloudwatch.namespace-aruba=Sign/Aruba
pn.ss.sign.cloudwatch.namespace-namirial=Sign/Namirial
pn.ss.sign.cloudwatch.dimension-metrics-schema=${PnSsSignAndTimemarkMetricsSchema:Pn-SS-SignAndTimemark-MetricsSchema}
pn.ss.sign.cloudwatch.metric-response-time.pades=SignPADESDocumentResponseTime
pn.ss.sign.cloudwatch.metric-response-time.cades=SignCADESDocumentResponseTime
pn.ss.sign.cloudwatch.metric-response-time.xades=SignXADESDocumentResponseTime
pn.ss.sign.cloudwatch.metric-dimension-file-size-range=FileSizeRange
pn.ss.sign.cloudwatch.publisher.maximum-calls-per-upload=${CloudWatchPublisherMaximumCallsPerUpload:10}
pn.ss.sign.cloudwatch.publisher.upload-frequency-millis=${CloudWatchPublisherUploadFrequencyMillis:60000}

##########################
###   Sign - Aruba     ###
##########################

aruba.server.address=${PnSsArubaServerAddress:https://asbr-pagopa.arubapec.it/ArubaSignService/ArubaSignService}
aruba.cert_id=${PnSsArubaCertId:AS0}
aruba.enabled.log=${PnSsArubaEnabledLog:false}
#configurazione per ambiente di sviluppo
aruba.sign.timeout=${PnSsArubaSignTimeout:1}
aruba.proxy.properties.mtom-enabled=true

##########################
###   Sign - Namirial  ###
##########################

pn.ss.sign.namirial.address=${PnSsNamirialServerAddress}
pn.ss.sign.namirial.max-connections=${PnEcNamirialServerMaxConnections}
pn.ss.sign.namirial.pending-acquire-timeout=${PnEcNamirialServerPendingAcquireTimeout}

##########################
###   Sign - Provider  ###
##########################

pn.ss.sign.provider-switch=${PnSignProviderSwitch:1970-01-01T00:00:00Z;aruba,2024-03-26T23:00:00Z;namirial}

pn.ss.sign.retry.strategy.max-attempts=${PnSsSignRetryStrategyMaxAttempts:3}
pn.ss.sign.retry.strategy.min-backoff=${PnSsSignRetryStrategyMinBackoff:2}

pn.ss.sign.identity-signature=${PnSsIdentitySignature:Pn-SS-SignAndTimemark}

##########################
###   Ignored update metadata ###
##########################

# S3 URI del file contenente le fileKey da ignorare nelle operazioni S3 dell'updateMetadata
# Se non valorizzata o vuota, vuol dire che la funzionalita' e' disattivata
pn.ss.ignored-update-metadata.list=${PnSsIgnoredUpdateMetadataList:}

##########################
###   Indexing         ###
##########################

#Nome del parameter store contenente il JSON di configurazione.
pn.ss.indexing.configuration-name=${PnSsIndexingConfiguration:Pn-SS-IndexingConfiguration}

#Chiave del tag che indica il numero di pagine di un documento
pn.ss.indexing.document-number-of-pages-tag-key=document_number_of_pages

##########################
###   Event handler    ###
##########################

#Safe clients
#lista di clients separati da punto e virgola (es. pn-delivery;pn-delivery-push)
#per disabilitare il check impostare il valore a DISABLED
pn.ss.safe-clients=${PnSsSafeClients}

pn.ss.event-handler.max-messages=${PnSsEventHandlerMaxMessages:10}
#transformation-service

pn.ss.transformation-service.max.messages=${PnSsTransformationServiceMaxMessages:10}

##########################
###   Transformation   ###
##########################

### Settings ###
pn.ss.transformation.max-thread-pool-size.sign-and-timemark=${SignAndTimemarkMaxThreadPoolSize}
pn.ss.transformation.max-thread-pool-size.sign=${SignMaxThreadPoolSize}
pn.ss.transformation.dummy-delay=250
pn.ss.transformation.config.parameter-name=${PnSsTransformationConfiguration}

### Transformation queues ###
pn.ss.transformation.queues.staging=${PnSsQueueNameStagingBucket}
pn.ss.transformation.queues.sign-and-timemark=${PnSsQueueNameSignAndTimemarkTransformation}
pn.ss.transformation.queues.sign=${PnSsQueueNameSignTransformation}
pn.ss.transformation.queues.dummy=${PnSsQueueNameDummyTransformation}
