logging.config=classpath:logback-base.xml
pn.env.runtime=PROD
spring.application.name=PN-SafeStorage
#Setting CloudWatch logging level to info, to make CloudWatchMetricPublisher logs visible.
logging.level.software.amazon.awssdk.metrics.publishers.cloudwatch=info

# Parametri di configurazione del TaskExecutor di Spring Boot
pn.ss.task.execution.pool.max-size=${PN_SS_TASK_EXECUTION_POOL_MAX_SIZE}
pn.ss.task.execution.pool.core-size=${PN_SS_TASK_EXECUTION_POOL_CORE_SIZE}
pn.ss.task.execution.pool.queue-capacity=${PN_SS_TASK_EXECUTION_POOL_QUEUE_CAPACITY}

spring.codec.max-in-memory-size=${SPRING_CODEC_MAX_IN_MEMORY_SIZE:10000000}

logging.level.it.pagopa.pnss=${PnSsLoggingLevelRoot:debug}
#logging.level.org.springframework.web = DEBUG

# Several ResponseStatusException found. If this prop is not set the reason of the exception is not shown in the api response body
server.error.include-message=always

spring.task.scheduling.pool.size=3
management.endpoints.web.exposure.include=health,metrics,loggers

#Sqs timeout delta
pn.ss.sqs.timeout.percent=${PnSsSqsTimeoutPercent}
pn.ss.sqs.timeout.managedQueues=${PnSsSqsTimeoutManagedQueues}
pn.ss.sqs.timeout.default-seconds=${PnSsSqsTimeoutDefaultSeconds}

#Sqs
pn.ss.sqs.retry.strategy.max-attempts=${PnSsSqsRetryStrategyMaxAttempts:3}
pn.ss.sqs.retry.strategy.min-backoff=${PnSsSqsRetryStrategyMinBackoff:3}

#Sqs EventHandler
pn.ss.sqs.event-handler.retry.strategy.max-attempts=${PnSsSqsEventHandlerRetryStrategyMaxAttempts:3}
pn.ss.sqs.event-handler.retry.strategy.min-backoff=${PnSsSqsEventHandlerRetryStrategyMinBackoff:3}

pn.ss.statemachine.retry.strategy.max-attempts=${PnSsStateMachineRetryStrategyMaxAttempts:3}
pn.ss.statemachine.retry.strategy.min-backoff=${PnSsStateMachineRetryStrategyMinBackoff:3}

##########################
###   PnSsConfig       ###
##########################

pn.ss.default.time-zone=${PnSsDefaultTimeZone:Europe/Rome}

# Bucket
pn.ss.bucket.hot-name=${PN_SS_BUCKET_NAME:PnSsBucketName}
pn.ss.bucket.stage-name=${PN_SS_STAGING_BUCKET_NAME:PnSsStagingBucketName}

# Dynamo - Repository manager tables
pn.ss.dynamo.repository-manager.anagrafica-client-name=${PN_SS_TABLE_NAME_ANAGRAFICA_CLIENT:pn-SsAnagraficaClient}
pn.ss.dynamo.repository-manager.tipologie-documenti-name=${PN_SS_TABLE_NAME_TIPOLOGIE_DOCUMENTI:pn-SsTipologieDocumenti}
pn.ss.dynamo.repository-manager.documenti-name=${PN_SS_TABLE_NAME_DOCUMENTI:pn-SsDocumenti}
pn.ss.dynamo.repository-manager.scadenza-documenti-name=${PN_SS_TABLE_NAME_SCADENZA_DOCUMENTI:pn-SsScadenzaDocumenti}
pn.ss.dynamo.repository-manager.tags-name=${PN_SS_TABLE_NAME_TAGS:pn-SsTags}

# Dynamo - Event stream
pn.ss.dynamo.event-stream.document-name=${PN_SS_TABLE_DOCUMENTI_STREAM_ARN:PnSsTableDocumentiStreamArn}
pn.ss.dynamo.event-stream.table-metadata=${PN_SS_TABLE_DOCUMENTI_STREAM_METADATI_TABLE:TableDocumentiStreamMetadatiTable}

# Dynamo - Retry strategy
pn.ss.dynamo.retry-strategy.max-attempts=${PnSsDynamoRetryStrategyMaxAttempts:3}
pn.ss.dynamo.retry-strategy.min-backoff=${PnSsDynamoRetryStrategyMinBackoff:3}

# Sqs - Availability
pn.ss.sqs.availability.sqs-name=${PN_SS_QUEUE_NAME_AVAILABILITY:pn-ss-availability-events-queue}

# Event bridge
pn.ss.event-bridge.disponibilita-documenti-name=${PN_SS_EVENT_BUS_NAME_EXTERNAL_NOTIFICATION:Pn-Ss-Notifications-Bus}

# Endpoint - State machine
pn.ss.endpoint.state-machine.base-path=/statemachinemanager
pn.ss.endpoint.state-machine.container-base-url=${STATE_MACHINE_BASE_URL:http://localhost:8082}
pn.ss.endpoint.state-machine.validate=${pn.ss.endpoint.state-machine.base-path}/validate/{processId}/{currStatus}

# Gestore repository - Retry strategy
pn.ss.gestore-repository.retry-strategy.max-attempts=${PnSsGestoreRepositoryRetryStrategyMaxAttempts:3}
pn.ss.gestore-repository.retry-strategy.min-backoff=${PnSsGestoreRepositoryRetryStrategyMinBackoff:3}

# S3 - Retry strategy
pn.ss.s3.retry-strategy.max-attempts=${PnSsS3RetryStrategyMaxAttempts:3}
pn.ss.s3.retry-strategy.min-backoff=${PnSsS3RetryStrategyMinBackoff:3}

# Client interni - Endpoint
pn.ss.client-interni.endpoint.doc-client=/safestorage/internal/v1/documents/%s
pn.ss.client-interni.endpoint.doc-client-post=/safestorage/internal/v1/documents
pn.ss.client-interni.endpoint.user-configuration=/safestorage/internal/v1/userConfigurations/%s
pn.ss.client-interni.endpoint.scadenza-documenti-post=/safestorage/internal/v1/scadenza-documenti
pn.ss.client-interni.endpoint.configuration-api-documents-config=/safe-storage/v1/configurations/documents-types
pn.ss.client-interni.endpoint.doc-types=/safestorage/internal/v1/doctypes/%s
pn.ss.client-interni.endpoint.tags-get=/safestorage/internal/v1/tags/%s
pn.ss.client-interni.endpoint.tags-put=/safestorage/internal/v1/documents/%s/tags

# Client interni - Header, query param, base url, jetty
pn.ss.client-interni.header.api-key=x-api-key
pn.ss.client-interni.header.pagopa-safestorage-cx-id=x-pagopa-safestorage-cx-id
#Header related to the correlationID in microservices calls
pn.ss.client-interni.header.correlation-id=x-pagopa-pn-cx-id
pn.ss.client-interni.query-param.presigned-url-trace-id=x-amzn-trace-id
pn.ss.client-interni.base-url=${INTERNAL_BASE_URL:http://localhost:8080}
pn.ss.client-interni.jetty.max-connections-per-destination=${maxConnectionsPerDestination:200}

# Retention
#ATTENZIONE: autorizzazione interna (vedi trasformazione file)
pn.ss.retention.default-internal-api-key-value=internal-api.key
#ATTENZIONE: autorizzazione interna (vedi trasformazione file)
pn.ss.retention.default-internal-client-id-value=internal
pn.ss.retention.object-lock-retention-mode=${PN_SS_BUCKET_LOCK_RETENTION_MODE:GOVERNANCE}
pn.ss.retention.days-to-ignore=${PN_SS_PRELOADED_DOCS_RETENTION_DAYS:7}

# Uri builder
pn.ss.uri-builder.presigned-url.duration-minutes-upload=${DURATION_MINUTES_UPLOAD:60}
pn.ss.uri-builder.presigned-url.duration-minutes-download=${DURATION_MINUTES_DOWNLOAD:60}
pn.ss.uri-builder.presigned-url.checksum-sha256-header=checksum-sha256
pn.ss.uri-builder.stay-hot-bucket-time-days=${STAY_HOT_TIME:2}
pn.ss.uri-builder.get-file-with-patch-configuration=${PN_SS_URI_BUILDER_GET_FILE_WITH_PATCH_CONFIGURATION:NONE}
#Http header related to the S3 headObjectResponse
pn.ss.uri-builder.restore-request-date-header-name=x-amz-restore-request-date
pn.ss.uri-builder.max-restore-time-cold=${PnSsGlacierMaxRestoreTime:18000}
pn.ss.uri-builder.initial-new-document-state=BOOKED

##########################
###   CloudWatch       ###
##########################

pn.ss.sign.cloudwatch.namespace-aruba=Sign/Aruba
pn.ss.sign.cloudwatch.namespace-namirial=Sign/Namirial
pn.ss.sign.cloudwatch.dimension-metrics-schema=${PN_SS_SIGN_AND_TIMEMARK_METRICS_SCHEMA:Pn-SS-SignAndTimemark-MetricsSchema}
pn.ss.sign.cloudwatch.metric-response-time.pades=SignPADESDocumentResponseTime
pn.ss.sign.cloudwatch.metric-response-time.cades=SignCADESDocumentResponseTime
pn.ss.sign.cloudwatch.metric-response-time.xades=SignXADESDocumentResponseTime
pn.ss.sign.cloudwatch.metric-dimension-file-size-range=FileSizeRange
pn.ss.sign.cloudwatch.publisher.maximum-calls-per-upload=${CloudWatchPublisherMaximumCallsPerUpload:10}
pn.ss.sign.cloudwatch.publisher.upload-frequency-millis=${CloudWatchPublisherUploadFrequencyMillis:60000}

##########################
###   Sign - Aruba     ###
##########################

aruba.server.address=${PnSsArubaServerAddress:https://asbr-pagopa.arubapec.it/ArubaSignService/ArubaSignService}
aruba.cert_id=${PN_SS_ARUBA_CERT_ID:AS0}
aruba.enabled.log=${PN_SS_ARUBA_ENABLED_LOG:false}
#configurazione per ambiente di sviluppo
aruba.sign.timeout=${PnSsArubaSignTimeout:1}
aruba.proxy.properties.mtom-enabled=true

##########################
###   Sign - Namirial  ###
##########################

pn.ss.sign.namirial.address=${PN_SS_NAMIRIAL_SERVER_ADDRESS}
pn.ss.sign.namirial.max-connections=${PN_EC_NAMIRIAL_SERVER_MAX_CONNECTIONS}
pn.ss.sign.namirial.pending-acquire-timeout=${PN_EC_NAMIRIAL_SERVER_PENDING_ACQUIRE_TIMEOUT}

##########################
###   Sign - Provider  ###
##########################

pn.ss.sign.provider-switch=${PN_SIGN_PROVIDER_SWITCH:1970-01-01T00:00:00Z;aruba,2024-03-26T23:00:00Z;namirial}

pn.ss.sign.retry.strategy.max-attempts=${PN_SS_SIGN_RETRY_STRATEGY_MAX_ATTEMPTS:3}
pn.ss.sign.retry.strategy.min-backoff=${PN_SS_SIGN_RETRY_STRATEGY_MIN_BACKOFF:2}

pn.ss.sign.identity-signature=${PN_SS_IDENTITY_SIGNATURE:Pn-SS-SignAndTimemark}

##########################
###   Ignored update metadata ###
##########################

# S3 URI del file contenente le fileKey da ignorare nelle operazioni S3 dell'updateMetadata
# Se non valorizzata o vuota, vuol dire che la funzionalita' e' disattivata
pn.ss.ignored-update-metadata.list=${PN_SS_IGNORED_UPDATE_METADATA_LIST:}

##########################
###   Indexing         ###
##########################

#Nome del parameter store contenente il JSON di configurazione.
pn.ss.indexing.configuration-name=${PN_SS_INDEXING_CONFIGURATION:Pn-SS-IndexingConfiguration}

#Chiave del tag che indica il numero di pagine di un documento
pn.ss.indexing.document-number-of-pages-tag-key=document_number_of_pages

##########################
###   Event handler    ###
##########################

#Safe clients
#lista di clients separati da punto e virgola (es. pn-delivery;pn-delivery-push)
#per disabilitare il check impostare il valore a DISABLED
pn.ss.safe-clients=${PN_SS_SAFE_CLIENTS}

pn.ss.event-handler.max-messages=${PN_SS_EVENT_HANDLER_MAX_MESSAGES:10}
#transformation-service

pn.ss.transformation-service.max.messages=${PN_SS_TRANSFORMATION_SERVICE_MAX_MESSAGES:10}

##########################
###   Transformation   ###
##########################

### Settings ###
pn.ss.transformation.max-thread-pool-size.sign-and-timemark=${SIGN_AND_TIMEMARK_MAX_THREAD_POOL_SIZE}
pn.ss.transformation.max-thread-pool-size.sign=${SIGN_MAX_THREAD_POOL_SIZE}
pn.ss.transformation.dummy-delay=250
pn.ss.transformation.config.parameter-name=${PN_SS_TRANSFORMATION_CONFIGURATION}

### Transformation queues ###
pn.ss.transformation.queues.staging=${PN_SS_QUEUE_NAME_STAGING_BUCKET}
pn.ss.transformation.queues.sign-and-timemark=${PN_SS_QUEUE_NAME_SIGN_AND_TIMEMARK_TRANSFORMATION}
pn.ss.transformation.queues.sign=${PN_SS_QUEUE_NAME_SIGN_TRANSFORMATION}
pn.ss.transformation.queues.dummy=${PN_SS_QUEUE_NAME_DUMMY_TRANSFORMATION}
