AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

  PnSsTableNameAnagrafica:
    Type: String
    Description: Description
  
  PnSsTableNameTipologie:
    Type: String
    Description: Description

  PnSsTableNameDocumenti:
    Type: String
    Description: Description

  PnSsQueueNameNotificaDisponibilita:
    Type: String
    Description: Description

  PnSsQueueNameStagingBucket:
    Type: String
    Description: Description

  PnSsEventRuleNameNotificaDisponibilita:
    Type: String
    Description: Description

  PnSsEventRuleNameStagingBucket:
    Type: String
    Description: Description

Resources:
  NullResource:
      Type: AWS::CloudFormation::WaitConditionHandle

  PnSsTableAnagrafica:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -   
          AttributeName: "name"
          AttributeType: "S"
        -   
          AttributeName: "APIKey"
          AttributeType: "S"
      KeySchema: 
        -   
          AttributeName: "name"
          KeyType: "HASH"
        -
          AttributeName: "APIKey"
          KeyType: "RANGE"
      #KinesisStreamSpecification:
      #  StreamArn: "String"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: false
        SSEType: "KMS"
      TableClass: "STANDARD"
      TableName: !Ref PnSsTableNameAnagrafica
    DeletionPolicy: Retain

  PnSsTableTipologie:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -   
          AttributeName: "tipoDocumento"
          AttributeType: "S"
      KeySchema: 
        -   
          AttributeName: "tipoDocumento"
          KeyType: "HASH"
      #KinesisStreamSpecification:
      #  StreamArn: "String"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: false
        SSEType: "KMS"
      TableClass: "STANDARD"
      TableName: !Ref PnSsTableNameTipologie
    DeletionPolicy: Retain

  PnSsTableDocumenti:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -   
          AttributeName: "checksum"
          AttributeType: "S"
      KeySchema: 
        -   
          AttributeName: "checksum"
          KeyType: "HASH"
      #KinesisStreamSpecification:
      #  StreamArn: "String"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: false
        SSEType: "KMS"
      TableClass: "STANDARD"
      TableName: !Ref PnSsTableNameDocumenti
    DeletionPolicy: Retain


Outputs:
    SampleOutput:
      Description: A Sample Output
      Value: 'na'