
package it.pagopa.pn.ms.be.service.sign.wsdl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ArubaSignServiceService", targetNamespace = "http://arubasignservice.arubapec.it/", wsdlLocation = "/ArubaSignService.wsdl")
public class ArubaSignServiceService
    extends Service
{

    private final static URL ARUBASIGNSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ARUBASIGNSERVICESERVICE_EXCEPTION;
    private final static QName ARUBASIGNSERVICESERVICE_QNAME = new QName("http://arubasignservice.arubapec.it/", "ArubaSignServiceService");

    static {
        ARUBASIGNSERVICESERVICE_WSDL_LOCATION = it.pagopa.pn.ms.be.service.sign.wsdl.ArubaSignServiceService.class.getResource("/wsdl/ArubaSignService.wsdl");
        WebServiceException e = null;
        if (ARUBASIGNSERVICESERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/ArubaSignService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        ARUBASIGNSERVICESERVICE_EXCEPTION = e;
    }

    public ArubaSignServiceService() {
        super(__getWsdlLocation(), ARUBASIGNSERVICESERVICE_QNAME);
    }

    public ArubaSignServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ARUBASIGNSERVICESERVICE_QNAME, features);
    }

    public ArubaSignServiceService(URL wsdlLocation) {
        super(wsdlLocation, ARUBASIGNSERVICESERVICE_QNAME);
    }

    public ArubaSignServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ARUBASIGNSERVICESERVICE_QNAME, features);
    }

    public ArubaSignServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ArubaSignServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ArubaSignService
     */
    @WebEndpoint(name = "ArubaSignServicePort")
    public ArubaSignService getArubaSignServicePort() {
        return super.getPort(new QName("http://arubasignservice.arubapec.it/", "ArubaSignServicePort"), ArubaSignService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ArubaSignService
     */
    @WebEndpoint(name = "ArubaSignServicePort")
    public ArubaSignService getArubaSignServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://arubasignservice.arubapec.it/", "ArubaSignServicePort"), ArubaSignService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ARUBASIGNSERVICESERVICE_EXCEPTION!= null) {
            throw ARUBASIGNSERVICESERVICE_EXCEPTION;
        }
        return ARUBASIGNSERVICESERVICE_WSDL_LOCATION;
    }

}
