
package it.pagopa.pn.ms.be.service.sign.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "TypeOfTransportNotImplemented", targetNamespace = "http://arubasignservice.arubapec.it/")
public class TypeOfTransportNotImplemented_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TypeOfTransportNotImplemented faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TypeOfTransportNotImplemented_Exception(String message, TypeOfTransportNotImplemented faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public TypeOfTransportNotImplemented_Exception(String message, TypeOfTransportNotImplemented faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: it.pagopa.pn.template.sign.wsdl.TypeOfTransportNotImplemented
     */
    public TypeOfTransportNotImplemented getFaultInfo() {
        return faultInfo;
    }

}
